Navbar auth status
codesydney/woc pull request #51
Opened 2021-06-04 05:20 UTC by xenia11

## Rationale

Added Sign Out option to Navbar once the user is logged in. Added a function when Sign Out button is clicked, the user will no longer be logged in and the page will redirect the user to the landing page.

## Advice for Reviewers & Testing Notes

Log in and click Sign Out button.

## Screenshots:

- Add a screenshot or two of your changes, where applicable.

## Task Name

- Issue Title
- 
#Issue 38

## Linting Checklist
- [X ] No commented code
- [X ] Code Formatted nicely (Prettier)
- [ X] PR your own code before you assign reviewers

2021-06-06 22:46 UTC, pgayoso approved these changes
Okay

2021-06-07 00:32 UTC, kimchirice requested changes
maybe you accidentally delete web/package-lock.json? add it back to the commit

2021-06-07 03:07 UTC, xenia11 commented
@kimchirice thanks for noticing! I'll fix that later.

2021-06-07 15:49 UTC, deBubz approved these changes

2021-06-07 15:49 UTC, merged