02 footer component
codesydney/woc pull request #64
Opened 2021-07-05 09:56 UTC by pgayoso

## Rationale

Create a footer component.

## Advice for Reviewers & Testing Notes

- I replicated the footer from https://womenofcolour.org.au/ .
- Added the contact information to the footer.
- I think that It have to much information for this web, maybe we can take out some.

## Screenshots:

- ![image](https://user-images.githubusercontent.com/81002561/124453522-cbf69800-ddca-11eb-993b-9555cb859871.png)

## Task Name

- Issue  EP_02 Footer component #42

## Linting Checklist
- [X] No commented code
- [ ] Code Formatted nicely (Prettier)
- [ ] PR your own code before you assign reviewers

2021-07-08 07:04 UTC, xenia11 requested changes
I don't think we need to put that second section on our footer for the membership portal. Also, try to see why the CICD test failed. Otherwise, seems good. :)

2021-07-09 12:32 UTC, deBubz commented
yep try and have a look at what errors the ci/cd(github actions) throw so you could find away to fix it

2021-07-24 10:54 UTC, xenia11 approved these changes

2021-08-07 09:24 UTC, deBubz approved these changes
good stuff

2021-08-07 09:24 UTC, merged