Humanitix integration
codesydney/woc pull request #71
Opened 2021-11-22 12:10 UTC by xenia11

## Rationale

I've change fetch method to axios when calling events on User Events. I set to show and call events two months prior to current date.

## Advice for Reviewers & Testing Notes

## Screenshots:

-
![Screenshot_10](https://user-images.githubusercontent.com/80079688/142859192-30f109af-8b4c-484e-96d8-fab315fb2557.png)

## Task Name

- Issue Title

## Linting Checklist
- [x ] No commented code
- [ x] Code Formatted nicely (Prettier)
- [ x] PR your own code before you assign reviewers

2021-12-02 14:36 UTC, deBubz requested changes

2021-12-02 14:36 UTC, deBubz commented on server/controller/events.controller.js
>  require('dotenv').config();
can this be also removed, its not needed here

2021-12-05 02:51 UTC, xenia11 commented on web/src/pages/userDashboard/userevents/UserEvents.jsx
> +        };
Yes, I kept getting the mistake "Can't perform a React state update on an unmounted component" or something similar, and It was the only way to fix the bug.

2021-12-05 03:21 UTC, xenia11 commented on server/package.json
> +    "axios": "^0.24.0",
Sure

2021-12-05 03:24 UTC, xenia11 commented on server/controller/events.controller.js
>  require('dotenv').config();
Hi Bao, do you mean to remove require('dotenv').config();?

I need the first line "const https = require('https')" in order to get the events, since Humanitix API Integration Documentation says that they need "https"

2021-12-05 03:50 UTC, deBubz commented on server/controller/events.controller.js
>  require('dotenv').config();
yep just remove the dotenv config, it doesnt need to be there

2021-12-06 21:47 UTC, xenia11 commented on server/controller/events.controller.js
>  require('dotenv').config();
Good morning @deBubz, I've just pushed the changes. Let me know if there is anything else. Cheers

2021-12-07 07:07 UTC, deBubz approved these changes

2021-12-07 07:13 UTC, merged