Landing page.v2
codesydney/woc pull request #97
Opened 2022-01-16 10:29 UTC by xenia11

## Rationale

Changed UI of the landing page

## Advice for Reviewers & Testing Notes

## Screenshots:

![Screenshot_11](https://user-images.githubusercontent.com/80079688/149656099-e0aa7f44-9ec5-453c-b1d2-5e0e5cf681c4.png)

![Screenshot_12](https://user-images.githubusercontent.com/80079688/149656105-67611f8b-60d0-4a29-98fe-738e643fcbf0.png)
![Screenshot_13](https://user-images.githubusercontent.com/80079688/149656107-2a371b2b-f9b1-495e-9f9e-ae34294d3e1f.png)

## Task Name

- Issue Title

- #96

## Linting Checklist
- [x ] No commented code
- [ x] Code Formatted nicely (Prettier)
- [ ] PR your own code before you assign reviewers

2022-01-16 23:28 UTC, engramar approved these changes
Perfect @xenia11! Great start! Thanks!

2022-01-18 06:43 UTC, deBubz requested changes
Also try to make the pass the CI/CD as well

```
src/components/layout/Layout.jsx
  Line 3:8:  'Footer' is defined but never used  no-unused-vars

src/pages/landing/Landing.jsx
  Line 4:27:  'Paper' is defined but never used  no-unused-vars
```

2022-01-18 06:43 UTC, deBubz commented on web/src/pages/landing/Landing.jsx
> +import landingSvg from "./../../res/img/WoCA logo.png";
Can you use the new convention

keep it as `"res/img/WoCA logo.png";` should woork

2022-01-18 06:43 UTC, deBubz commented on web/src/pages/userDashboard/UserDashboard.jsx
> +import Footer from "./../../components/footer/Footer";
you dont need to traverse through the folders anymore
you can get to any folder in src as absolute path
`"./../../components/footer/Footer";`

2022-01-21 06:30 UTC, xenia11 commented
@deBubz Hi Bao, CICD works now. Should I push it to dev now?

2022-01-21 11:30 UTC, deBubz approved these changes

2022-01-21 11:30 UTC, merged